#!/usr/bin/env perl
use strict;
use warnings;

use lib map { "$ENV{HOME}/sandbox/$_/lib" } qw(MIDI-Chord-Guitar MIDI-Util);
use MIDI::Chord::Guitar;
use MIDI::Util;

my $score = MIDI::Util::setup_score(patch => 24);

my $mcg = MIDI::Chord::Guitar->new;

# Progression: iv7–VII7–IIImaj7–VImaj7–iiø7–V7–i

my $chord = $mcg->transform('C3', 'm7');
$score->n('wn', @$chord);

$chord = $mcg->transform('F3', '7');
$score->n('wn', @$chord);

$chord = $mcg->transform('Bb2', 'maj7');
$score->n('wn', @$chord);

$chord = $mcg->transform('Eb3', 'maj7');
$score->n('wn', @$chord);

$chord = $mcg->transform('A3', 'dim7');
$score->n('wn', @$chord);

$chord = $mcg->transform('D3', '7');
$score->n('wn', @$chord);

$chord = $mcg->transform('G2', 'm');
$score->n('wn', @$chord);

$score->write_score("$0.mid");
