#!/usr/bin/env perl
use strict;
use warnings;

use lib map { "$ENV{HOME}/sandbox/$_/lib" } qw(MIDI-Chord-Guitar MIDI-Util);
use MIDI::Chord::Guitar;
use MIDI::Util;

my $score = MIDI::Util::setup_score(patch => 24);

my $mcg = MIDI::Chord::Guitar->new;

# Progression: iv7–VII7–IIImaj7–VImaj7–iiø7–V7–i

for my $spec (
    ['C3', 'm7', 0],
    ['F3', '7', 0],
    ['Bb2', 'maj7', 0],
    ['Eb3', 'maj7', 0],
    ['A3', 'dim7', 0],
    ['D3', '7', 0],
    ['G2', 'm', 0],
) {
    my $chord = $mcg->transform(@$spec);
    $score->n('qn', $chord->[0]);
    $score->n('dhn', @{$chord}[1 .. $#$chord]);
}

$score->write_score("$0.mid");
